Fetch15 twitter with base64 images
knorth55/jsk_3rdparty pull request #31
Opened 2022-08-22 06:19 UTC by iory

fetchでtweetするときにbase64の画像を読み込んで、画像つきでtweetすることを可能にする変更です。
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/375
こちらのPRがupstreamのものです。

@tkmtnt7000
https://github.com/knorth55/jsk_robot/pull/327 こちらのPRでキッチンデモをやってみたときにtweetが画像つきで表示されるのかを確認してみてください。

2022-08-22 06:20 UTC, tkmtnt7000 commented
ありがとうございます．早速試してみます．

2022-08-22 06:52 UTC, tkmtnt7000 requested changes

2022-08-22 06:52 UTC, tkmtnt7000 commented on rostwitter/python/rostwitter/twitter.py
> +from itertools import zip_longest
This line is only for python3.
Maybe `from itertools import izip_longest` is for python2

2022-08-22 07:10 UTC, tkmtnt7000 requested changes

2022-08-22 07:10 UTC, tkmtnt7000 commented on rostwitter/python/rostwitter/twitter.py
> +        for text, media_list in zip_longest(texts, split_media_list):
This line is also only for python3. 
I use izip_longest and successfully run kitchen-demo.

2022-08-22 07:13 UTC, tkmtnt7000 commented
I tested this feature with kitchen-demo. 
See https://twitter.com/fetch_jsk/status/1561611173945978880, https://twitter.com/fetch_jsk/status/1561611164689510400, https://twitter.com/fetch_jsk/status/1561611144800120832, ... etc.

2022-08-22 08:41 UTC, iory commented on rostwitter/python/rostwitter/twitter.py
> +from itertools import zip_longest
Thanks! Fixed it. https://github.com/knorth55/jsk_3rdparty/pull/31/commits/8186633a7e9defb7ca3777624424250d8dc29b42

2022-08-22 08:41 UTC, iory commented on rostwitter/python/rostwitter/twitter.py
> +        for text, media_list in zip_longest(texts, split_media_list):
Thanks! Fixed it. https://github.com/knorth55/jsk_3rdparty/pull/31/commits/8186633a7e9defb7ca3777624424250d8dc29b42

2022-08-22 08:43 UTC, iory commented
@tkmtnt7000 Thanks!

https://github.com/tkmtnt7000/jsk_robot/pull/7
I made a change to see it as a THREAD when tweeting.
It would be great if you could check again.

2022-08-22 16:11 UTC, tkmtnt7000 requested changes

2022-08-22 16:11 UTC, tkmtnt7000 commented on rostwitter/python/rostwitter/twitter.py
> +except (ImportError, ModuleNotFoundError):
Sorry `ModuleNotFoundError` may be also only for python3.
```suggestion
except ImportError:
```

2022-08-22 16:39 UTC, iory commented on rostwitter/python/rostwitter/twitter.py
> +except (ImportError, ModuleNotFoundError):
Thanks!

2022-08-24 09:04 UTC, tkmtnt7000 commented
I think it's time to merge this PR, could you please add commit if you have something to update and if you have time? @iory

2022-08-25 04:41 UTC, iory commented
Thanks. I added commit of upstream https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/375

2022-08-25 04:56 UTC, tkmtnt7000 commented
Thank you for updating. It looks good.

2022-08-25 04:57 UTC, tkmtnt7000 approved these changes

2022-08-25 08:57 UTC, iory commented
@tkmtnt7000 Thanks for your review! Merge this PR.

2022-08-25 08:57 UTC, merged